const words = {
  numRows: 11,
  numCols: 15,
  padTop: 1,
  padRight: 2,
  padBottom: 2,
  padLeft: 2,
  list: [
    {
      dir: "down",
      letters: "HAMMERHEAD",
      row: 0,
      col: 11,
      room: "end",
      acrostic: [
        "How do you do it?",
        "Another slap across the face",
        "Mousetraps and miracles like friendless allegories",
        "Marked, indulged, and catalogued",
        "Eating all night long",
        "Remembering at the last second to wash their hands",
        "Hollering plaintive formless tyrant",
        "Elude prodding veins, those climbing things",
        "All alone in this ceaseless striving",
        "Dead before you knew their names",
      ],
    },
    {
      dir: "down",
      letters: "LOQUAT",
      row: 3,
      col: 9,
      room: "start",
      acrostic: [
        "Lo, whose iridescent wings are these that draw the eyes of flowers?",
        "Our poet of the hour",
        "Queen of Wands and pens and keys",
        "Upon her throne of lions",
        "Accuse her NOT of being demure",
        "This is one crow you won't find sitting near the garbage can",
      ],
    },
    {
      dir: "across",
      letters: "TIMETRAVEL",
      row: 8,
      col: 5,
      room: "end",
      acrostic: [
        "Take comfort in the smallness of life",
        "In the insignificance of crowns and precious metals",
        "Make a nest from silver thread, baby's breath, silk",
        "Every precious thing at his talontips",
        "This is one crow you won't find sitting near the garbage can",
        "Rhinestons, velvet, platform boots, he fancies himself a peacock",
        "All alone in this ceaseless striving",
        "Veils are thin in his kingdom",
        "Eternal twinkles, turning of heads, and shattering spotlight",
        "Laughter and tears of despair and fat snowflakes settling upon the black",
      ],
    },
    {
      dir: "across",
      letters: "LOVE",
      row: 4,
      col: 8,
      room: "start",
      acrostic: [
        "Luke Bickerstaff's Worst Favorite Person of the Year",
        "Our poet of the hour",
        "Vampires, we know, have a lecherous proclivity",
        "Eating all night long",
      ],
    },
    {
      dir: "down",
      letters: "QUARTER",
      row: 4,
      col: 5,
      room: "end",
      acrostic: [
        "Question everything unseen",
        "Undress the naked world",
        "And find underneath silent film",
        "Registers of unwallowed pain",
        "The stars are ageless, aren't they?",
        "Eternal twinkles, turning of heads, and shattering spotlight",
        "Return to the glamour of FACES!",
      ],
    },
    {
      dir: "down",
      letters: "ARMATURE",
      row: 1,
      col: 13,
      room: "start",
      acrostic: [
        "Are you still awake, mein Geschöpf?",
        "Rest will find your cracked clay hands nestled underground",
        "Making it up as you",
        "Angels and monsters are not so different",
        "Take comfort in the smallness of life",
        "Undulating in unison, these serpents find themselves full of joy",
        "Regression in a natural part of the process",
        "Ein Kobold kann ohne ein Wiegenlied nicht schlafen",
      ],
    },
    {
      dir: "across",
      letters: "SEAFOAM",
      row: 6,
      col: 0,
      room: "start",
      acrostic: [
        "So, do you like it so far?",
        "Even the best of us must sometimes stand on our heads",
        "Attend our lives walking backwards for a while",
        "Failing up or upsidedown",
        "Oracles, poets, wise men, and witches—fools and desperados",
        "And here you find yourself",
        "Making it up as you go",
      ],
    },
  ],
};
